services:
  vector.search:
    image: ${DOCKER_REGISTRY-}vector.search
    container_name: vector.search
    build:
      context: ./src
      dockerfile: Vector.Search/Dockerfile
      args:
        - AUTHORS=${AUTHORS}
        - VERSION=${VERSION}
        - TITLE=${TITLE}
        - DESCRIPTION=${DESCRIPTION}
        - BUILD_DATE=${BUILD_DATE}
    environment:
      OLLAMA_BASEURL: http://ollama:11434
      EMBEDDING_MODEL: nomic-embed-text
      CHAT_MODEL: llama3.1
      REPO_ROOT: /repo
      DELETE_TEMP_FILES: "false"
      FILE_EXTENSIONS: .cs,.json,.yml,.yaml,.csproj,.props,.targets,.md,.sql,.js,.tsx,.ts,.html,.css,.ps1,.csproj
    volumes:
      - .\repo:/repo:ro
    ports:
      - 9020:8081
    networks:
      - vector_search_network
    depends_on:
      seq:
        condition: service_started
      ollama:
        condition: service_healthy
      openwebui:
        condition: service_started
      pgvector:
        condition: service_healthy
    user: "1654:1654"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ollama:/root/.ollama
    networks:
      - vector_search_network
    restart: always
    healthcheck:
      test: ["CMD", "ollama", "list"] # The recommended health check command      
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    environment:
      - ENV=dev
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vector_search_network
    restart: always

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - vector_search_network
    volumes:
      - seq_data:/data
    restart: always

  pgvector:
    image: pgvector/pgvector:pg18
    container_name: pgvector
    restart: always
    ports:
      - 5432:5432
    networks:
      - vector_search_network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=vector_search 
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgvector:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 3
 
networks:
  vector_search_network:
    driver: bridge

volumes:
  seq_data:
  ollama:
  open-webui:
  repo:
  pgvector:
