services:
  vector.search:
    image: ${DOCKER_REGISTRY-}vector.search
    container_name: vector.search
    build:
      context: ./src
      dockerfile: Vector.Search/Dockerfile
      args:
        - AUTHORS=${AUTHORS}
        - VERSION=${VERSION}
        - TITLE=${TITLE}
        - DESCRIPTION=${DESCRIPTION}
        - BUILD_DATE=${BUILD_DATE}
    environment:
      OLLAMA_BASEURL: http://ollama:11434
      QDRANT_URL: http://qdrant:6333
      QDRANT_COLLECTION: code_chunks
      EMBEDDING_MODEL: nomic-embed-text
      CHAT_MODEL: llama3.1
      REPO_ROOT: /repo
      FILE_EXTENSIONS: .cs,.json,.yml,.yaml,.csproj,.props,.targets,.md,.sql,.js,.tsx,.ts,.html,.css,.ps1
    volumes:
      - repo:/repo:ro
    ports:
      - 9020:8081
    networks:
      - vector_search_network
    depends_on:
      seq:
        condition: service_started
      ollama:
        condition: service_started
      openwebui:
        condition: service_started
      qdrant:
        condition: service_started
    user: "1654:1654"

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_MAX_LOADED_MODELS=1
    volumes:
      - ollama:/root/.ollama
    networks:
      - vector_search_network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 8080:8080
    environment:
      - ENV=dev
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vector_search_network
    restart: always

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:5341
      - 8081:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_FIRSTRUN_ADMINPASSWORD}
    networks:
      - vector_search_network
    volumes:
      - seq_data:/data
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      # 6333: REST API (HTTP) & Web UI
      - "6333:6333"
      # 6334: gRPC API
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335    
    configs:
      - source: qdrant_config    
    volumes:
      - qdrant_data:/qdrant/storage

networks:
  vector_search_network:
    driver: bridge

configs:
  qdrant_config:
    content: |
      log_level: INFO

volumes:
  seq_data:
  ollama:
  open-webui:
  qdrant_data:
  repo:
